workflow:
  name: 'Test Pipeline'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  stages:
    - build
    - deploy

# build stage
build_app:
  image: node:alpine
  stage: build
  only:
    - merge_requests
  script:
    - npm install
    - npm install yarn -g
    - yarn build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

# production stage
production:
  image: python:alpine
  stage: deploy
  only:
    - merge_requests
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://vivahome-admin