include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - build
  - deploy

# build stage
build_app:
  image: node:alpine
  stage: build
  only:
    - main
  script:
    - npm install
    - npm install yarn -g
    - yarn build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

# production stage
production:
  image: python:alpine
  stage: deploy
  only:
    - main
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://vivahome-admin