include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - build
  - deploy

# build stage
build_app:
  image: node:alpine
  stage: build
  only:
    - main
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  script:
    - yarn install --cache-folder .yarn
    - yarn build
  cache:
    paths:
      - node_modules/
      - .yarn
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

# production stage
production:
  image: python:alpine
  stage: deploy
  only:
    - main
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://vivahome-admin