export default {
  groups: [
    {
      id: 1,
      subject: 'permissions',
      slug: 'menu_group_general',
      items: [
        {
          id: 1,
          action: 'list-all',
          slug: 'menu_item_dashboard',
          icon: 'view-dashboard',
          route: 'dashboard',
          method: null,
          disabled: false,
        },
      ],
    },
    {
      id: 2,
      subject: 'property',
      slug: 'menu_group_properties',
      items: [
        {
          id: 2,
          action: 'list-all',
          slug: 'menu_item_properties_list',
          icon: 'home-city',
          route: 'propertiesCatalogue',
          method: null,
          disabled: false,
        },
        {
          id: 3,
          action: 'view',
          slug: 'menu_item_properties_index',
          icon: 'folder-home',
          route: 'propertiesIndex',
          method: null,
          disabled: false,
        },
        {
          id: 4,
          action: 'store',
          slug: 'menu_item_property_create',
          icon: 'home-plus',
          route: 'propertyCreate',
          method: null,
          disabled: false,
        },
      ],
    },
    {
      id: 3,
      subject: 'client',
      slug: 'menu_group_clients',
      items: [
        {
          id: 5,
          action: 'list-all',
          slug: 'menu_item_clients_list',
          icon: 'account-group',
          route: 'clientsList',
          method: null,
          disabled: false,
        },
        {
          id: 6,
          action: 'view',
          slug: 'menu_item_clients_index',
          icon: 'folder-account',
          route: 'clientsIndex',
          method: null,
          disabled: true,
        },
        {
          id: 7,
          action: 'store',
          slug: 'menu_item_client_create',
          icon: 'account-plus',
          route: 'clientCreate',
          method: null,
          disabled: false,
        },
      ],
    },
    {
      id: 4,
      subject: 'user',
      slug: 'menu_group_brokers',
      label: 'Brokers',
      items: [
        {
          id: 8,
          action: 'list-all',
          slug: 'menu_item_brokers_list',
          label: 'Broker List',
          icon: 'format-list-text',
          route: 'brokersList',
          method: null,
          disabled: false,
        },
        {
          id: 9,
          action: 'store',
          slug: 'menu_item_broker_create',
          label: 'Create New Broker',
          icon: 'briefcase-plus',
          route: 'brokerCreate',
          method: null,
          disabled: false,
        },
      ],
    },
  ],
  app: [
    {
      id: 10,
      action: 'list-all',
      slug: 'menu_item_settings_index',
      icon: 'cog',
      route: 'settings',
      method: null,
      disabled: true,
    },
    {
      id: 11,
      action: null,
      slug: 'menu_item_action_logout',
      icon: 'logout',
      route: null,
      method: 'logout',
      disabled: false,
    },
  ],
};
