export default {
  1: {
    id: 1,
    slug: 'kitchen',
    title: 'Kitchen',
    icon: 'countertop-outline',
  },
  2: {
    id: 2,
    slug: 'internet',
    title: 'Internet & TV',
    icon: 'wifi',
  },
  3: {
    id: 3,
    slug: 'elevator',
    title: 'Elevator',
    icon: 'elevator-passenger-outline',
  },
  4: {
    id: 4,
    slug: 'garage',
    title: 'Garage',
    icon: 'garage-variant',
  },
  5: {
    id: 5,
    slug: 'parking_space',
    title: 'Parking Space',
    icon: 'car-brake-parking',
  },
  6: {
    id: 6,
    slug: 'mortgaged',
    title: 'Mortgaged',
    icon: 'home-import-outline',
  },
  7: {
    id: 7,
    slug: 'needs_renovation',
    title: 'Needs Renovation',
    icon: 'account-hard-hat-outline',
  },
  8: {
    id: 8,
    slug: 'working_business',
    title: 'Working Business',
    icon: 'handshake-outline',
  },
  9: {
    id: 9,
    slug: 'furnished',
    title: 'Furnished',
    icon: 'sofa-outline',
  },
  10: {
    id: 10,
    slug: 'possible_barter',
    title: 'Possible Barter',
    icon: 'home-switch-outline',
  },
  11: {
    id: 11,
    slug: 'security',
    title: 'Security',
    icon: 'shield-home',
  },
  12: {
    id: 12,
    slug: 'entrance_control',
    title: 'Entrance Control',
    icon: 'cctv',
  },
  13: {
    id: 13,
    slug: 'residential_complex',
    title: 'Residential Complex',
    icon: 'sitemap-outline',
  },
  14: {
    id: 14,
    slug: 'railroad_apartment',
    title: 'Railroad Apartment',
    icon: 'map-marker-path',
  },
};
